// <------------------------------------------------------------------------------------------------------------------------------------------------------>
// Team`s Information
/*
  Information of the teams and players.
  For now is used const, but when trade players between teams change for let
*/
let teams = [
  { name: "Corinthians",
    players: [
    {name: "Cássio", position: "GK", hability: 48, redCard: 0, yellowCard: 0, gols: 0},
    {name: "Walter", position: "GK", hability: 46, redCard: 0, yellowCard: 0, gols: 0},
    {name: "C. França", position: "GK", hability: 40, redCard: 0, yellowCard: 0, gols: 0},
    {name: "Fagner", position: "DE", hability: 47, redCard: 0, yellowCard: 0, gols: 0},
    {name: "Gil", position: "DE", hability: 47, redCard: 0, yellowCard: 0, gols: 0},
    {name: "Manoel", position: "DE", hability: 45, redCard: 0, yellowCard: 0, gols: 0},
    {name: "D. Avelar", position: "DE", hability: 44, redCard: 0, yellowCard: 0, gols: 0},
    {name: "B. Mendez", position: "DE", hability: 40, redCard: 0, yellowCard: 0, gols: 0},
    {name: "Ralf", position: "MF", hability: 42, redCard: 0, yellowCard: 0, gols: 0},
    {name: "Jr. Urso", position: "MF", hability: 46, redCard: 0, yellowCard: 0, gols: 0},
    {name: "Sornoza", position: "MF", hability: 44, redCard: 0, yellowCard: 0, gols: 0},
    {name: "Pedrinho", position: "MF", hability: 47, redCard: 0, yellowCard: 0, gols: 0},
    {name: "M. Vital", position: "MF", hability: 47, redCard: 0, yellowCard: 0, gols: 0},
    {name: "Clayson", position: "OF", hability: 45, redCard: 0, yellowCard: 0, gols: 0},
    {name: "Everaldo", position: "OF", hability: 42, redCard: 0, yellowCard: 0, gols: 0},
    {name: "Gustagol", position: "OF", hability: 43, redCard: 0, yellowCard: 0, gols: 0},
    {name: "M. Boselli", position: "OF", hability: 44, redCard: 0, yellowCard: 0, gols: 0},
    {name: "V. Love", position: "OF", hability: 45, redCard: 0, yellowCard: 0, gols: 0}
    ], nameCoach: "Fabio Carille"
},
  { name: "Palmeiras",
    players: [
    {name: "F. Prass", position: "GK", hability: 41, redCard: 0, yellowCard: 0, gols: 0},
    {name: "Jailson", position: "GK", hability: 43, redCard: 0, yellowCard: 0, gols: 0},
    {name: "Weverton", position: "GK", hability: 46, redCard: 0, yellowCard: 0, gols: 0},
    {name: "M. Rocha", position: "DE", hability: 46, redCard: 0, yellowCard: 0, gols: 0},
    {name: "D.Barbosa", position: "DE", hability: 45, redCard: 0, yellowCard: 0, gols: 0},
    {name: "Luan", position: "DE", hability: 46, redCard: 0, yellowCard: 0, gols: 0},
    {name: "G. Gómez", position: "DE", hability: 47, redCard: 0, yellowCard: 0, gols: 0},
    {name: "V. Hugo", position: "DE", hability: 45, redCard: 0, yellowCard: 0, gols: 0},
    {name: "F. Melo", position: "MF", hability: 48, redCard: 0, yellowCard: 0, gols: 0},
    {name: "B. Henrique", position: "MF", hability: 45, redCard: 0, yellowCard: 0, gols: 0},
    {name: "Ramires", position: "MF", hability: 42, redCard: 0, yellowCard: 0, gols: 0},
    {name: "Zé Rafael", position: "MF", hability: 44, redCard: 0, yellowCard: 0, gols: 0},
    {name: "G. Scarpa", position: "MF", hability: 46, redCard: 0, yellowCard: 0, gols: 0},
    {name: "Dudu", position: "OF", hability: 48, redCard: 0, yellowCard: 0, gols: 0},
    {name: "L. Adriano", position: "OF", hability: 46, redCard: 0, yellowCard: 0, gols: 0},
    {name: "Borja", position: "OF", hability: 42, redCard: 0, yellowCard: 0, gols: 0},
    {name: "W. Bigode", position: "OF", hability: 43, redCard: 0, yellowCard: 0, gols: 0},
    {name: "Deyverson", position: "OF", hability: 40, redCard: 0, yellowCard: 0, gols: 0},
  ], nameCoach: "Mano Menezes"
},  
  { name: "São Paulo",
  players: [
  {name: "T. Volpi", position: "GK", hability: 45, redCard: 0, yellowCard: 0, gols: 0},
  {name: "Jean", position: "GK", hability: 44, redCard: 0, yellowCard: 0, gols: 0},
  {name: "Junior", position: "GK", hability: 40, redCard: 0, yellowCard: 0, gols: 0},
  {name: "Juanfran", position: "DE", hability: 44, redCard: 0, yellowCard: 0, gols: 0},
  {name: "Reinaldo", position: "DE", hability: 43, redCard: 0, yellowCard: 0, gols: 0},
  {name: "B. Alves", position: "DE", hability: 45, redCard: 0, yellowCard: 0, gols: 0},
  {name: "Arboleda", position: "DE", hability: 46, redCard: 0, yellowCard: 0, gols: 0},
  {name: "A. Martins", position: "DE", hability: 42, redCard: 0, yellowCard: 0, gols: 0},
  {name: "Tche Tche", position: "MF", hability: 45, redCard: 0, yellowCard: 0, gols: 0},
  {name: "Liziero", position: "MF", hability: 44, redCard: 0, yellowCard: 0, gols: 0},
  {name: "Hernanes", position: "MF", hability: 46, redCard: 0, yellowCard: 0, gols: 0},
  {name: "Dani Alves", position: "MF", hability: 48, redCard: 0, yellowCard: 0, gols: 0},
  {name: "Éverton", position: "MF", hability: 45, redCard: 0, yellowCard: 0, gols: 0},
  {name: "Antony", position: "OF", hability: 47, redCard: 0, yellowCard: 0, gols: 0},
  {name: "Pablo", position: "OF", hability: 46, redCard: 0, yellowCard: 0, gols: 0},
  {name: "Raniel", position: "OF", hability: 45, redCard: 0, yellowCard: 0, gols: 0},
  {name: "A. Pato", position: "OF", hability: 47, redCard: 0, yellowCard: 0, gols: 0},
  {name: "J. Toró", position: "OF", hability: 42, redCard: 0, yellowCard: 0, gols: 0},
], nameCoach: "Cuca"  
},
  { name: "Santos",
  players: [
  {name: "Vanderlei", position: "GK", hability: 48, redCard: 0, yellowCard: 0, gols: 0},
  {name: "Everson", position: "GK", hability: 47, redCard: 0, yellowCard: 0, gols: 0},
  {name: "John", position: "GK", hability: 40, redCard: 0, yellowCard: 0, gols: 0},
  {name: "V. Ferraz", position: "DE", hability: 45, redCard: 0, yellowCard: 0, gols: 0},
  {name: "Jorge", position: "DE", hability: 48, redCard: 0, yellowCard: 0, gols: 0},
  {name: "L. Veríssimo", position: "DE", hability: 46, redCard: 0, yellowCard: 0, gols: 0},
  {name: "G. Henrique", position: "DE", hability: 47, redCard: 0, yellowCard: 0, gols: 0},
  {name: "F. Aguilar", position: "DE", hability: 44, redCard: 0, yellowCard: 0, gols: 0},
  {name: "Alisson", position: "MF", hability: 45, redCard: 0, yellowCard: 0, gols: 0},
  {name: "D. Pituca", position: "MF", hability: 47, redCard: 0, yellowCard: 0, gols: 0},
  {name: "C. Sánchez", position: "MF", hability: 48, redCard: 0, yellowCard: 0, gols: 0},
  {name: "J. Mota", position: "MF", hability: 46, redCard: 0, yellowCard: 0, gols: 0},
  {name: "C. Cueva", position: "MF", hability: 44, redCard: 0, yellowCard: 0, gols: 0},
  {name: "Y. Solteldo", position: "OF", hability: 48, redCard: 0, yellowCard: 0, gols: 0},
  {name: "Marinho", position: "OF", hability: 47, redCard: 0, yellowCard: 0, gols: 0},
  {name: "D. González", position: "OF", hability: 45, redCard: 0, yellowCard: 0, gols: 0},
  {name: "E. Sasha", position: "OF", hability: 45, redCard: 0, yellowCard: 0, gols: 0},
  {name: "Kaio", position: "OF", hability: 42, redCard: 0, yellowCard: 0, gols: 0},
], nameCoach: "Jorge Sampaoli"  
},
]